#!/bin/python

print("Hello, and welcome to my interpretation of a traditional Mastermind\ngame!\nMastermind is a classic game that entails one player guessing a set\nof colors, in order, that is generated by another player.  For this version,\n I'll be the player who creates the random color sequence, and you'll have\n to guess what it is.  If you want to hear more about the rules of the game,\ntype y now; otherwise type n (don't type anything besides that...I don't\nwant to write a handler for a bad input...)\n\n")

response = input("y/n?\n")

if response == "y":
    print("Okay, so there are 8 different colors in the game: red, orange, yellow,\ngreen, blue, violet, black, and brown.  When you start the game, I will\nrandomly select a sequence of 5 colors, and some of these colors might be the same.\nYour job is to give me an initial guess on the colors I picked.\nI'll ask you for your guesses in order, because I have the colors you're guessing\norganized in a particular order that you have to match.  After you almost\ncertainly get it incorrect the first time, I'll let you know how you did; if\nyou get a correct color in a correct location, I'll let you know you'll\nguess again with a new sequence.  This process repeats until either you get it\nright or I get bored (so many 10 tries or so).  Good luck!\n\n")
elif response == "n":
    print("Excellent, you must be a Mastermind veteran\n\n")
else:
    print("Ha, gottem, I did write a handler, and you're not allowed to do that.\nSince you didn't follow the rules, I'll just assume you know what you're doing and we'll\ncontinue.\n\n")

import random

colorList = ["red", "orange", "yellow", "green", "blue", "violet", "black", "brown"]

thisGame = ["color"] * 5

for x in range(0,5):
    thisGame[x] = random.choice(colorList)

i = 0

while i < 10 && win == 0:
    shock1 = 0
    shock2 = 0
    shock3 = 0
    shock4 = 0
    shock5 = 0
    win = 0
    guess1 = input("Guess the first color: ")
    guess2 = input("Guess the second color: ")
    guess3 = input("Guess the third color: ")
    guess4 = input("Guess the fourth color: ")
    guess5 = input("Guess the fifth color: ")

    if guess1 == thisGame[0]:
        print("You got the first one right!")
        shock1 = 1

    if guess2 == thisGame[1]:
        print("You got the second one right!")
        shock2 = 1

    if guess3 == thisGame[2]:
        print("You got the third one right!")
        shock3 = 1

    if guess4 == thisGame[3]:
        print("You got the fourth one right!")
        shock4 = 1

    if guess5 == thisGame[4]:
        print("You got the fifth one right!")
        shock5 = 1

    if guess1 == guess2 == guess3 == guess4 == guess5 == 1:
        print("You got them all! You win!")
        win = 1
