#!/bin/python

print("Hello, and welcome to my interpretation of a traditional Mastermind\ngame!\nMastermind is a classic game that entails one player guessing a set\nof colors, in order, that is generated by another player.  For this version,\n I'll be the player who creates the random color sequence, and you'll have\n to guess what it is.  If you want to hear more about the rules of the game,\ntype y now; otherwise type n (don't type anything besides that...I don't\nwant to write a handler for a bad input...)\n\n")
